# Generated by Django 4.2.11 on 2024-05-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaNome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_id', models.CharField(max_length=64, unique=True)),
                ('numero', models.CharField(max_length=16)),
                ('data_emissao', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recebida_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('E', 'Entregue'), ('A', 'Aguardando'), ('C', 'Cancelada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=16, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('fone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(blank=True, max_length=4, null=True)),
                ('municipio', models.CharField(blank=True, max_length=32, null=True)),
                ('bairro', models.CharField(blank=True, max_length=32, null=True)),
                ('endereco', models.CharField(blank=True, max_length=128, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('cep', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPrateleira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localNome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aberto', 'aberto'), ('Realizado', 'realizado'), ('Cancelado', 'cancelado')], max_length=20)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.categoria')),
                ('local', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.localprateleira')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setorNome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.produto')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.setor')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveBigIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='hello.ProdutoPedido', to='hello.produto'),
        ),
        migrations.CreateModel(
            name='ItemNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32)),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=8)),
                ('quantidade', models.CharField(max_length=32)),
                ('preco_unitario', models.CharField(max_length=32)),
                ('valot_total', models.CharField(max_length=32)),
                ('entrada', models.CharField(max_length=2)),
                ('data_importacao', models.DateTimeField(auto_now=True)),
                ('nfe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'COMPRA'), ('D', 'DOAÇÃO')], max_length=16)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.produto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.fornecedor'),
        ),
    ]
