# Generated by Django 4.2.11 on 2024-04-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='usuario',
        ),
    ]
