# Generated by Django 4.2.11 on 2024-05-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnf',
            name='codigo',
            field=models.CharField(max_length=64),
        ),
    ]
