# Generated by Django 4.2.11 on 2024-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(default=12345678, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='tipo',
            field=models.CharField(choices=[('C', 'COMPRA'), ('D', 'DOAÇÃO')], max_length=16),
        ),
    ]
