# Generated by Django 4.2.13 on 2024-05-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnf',
            name='data_importacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemnf',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemnf',
            name='entrada',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemnf',
            name='nfe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemnf',
            name='preco_unitario',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemnf',
            name='quantidade',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemnf',
            name='unidade',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemnf',
            name='valot_total',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='recebida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
