# Generated by Django 4.1.7 on 2023-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], max_length=20),
        ),
    ]
