# Generated by Django 4.2.11 on 2024-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_itemnf_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnf',
            name='preco_unitario',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='itemnf',
            name='quantidade',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='itemnf',
            name='valor_total',
            field=models.CharField(max_length=64),
        ),
    ]
