# Generated by Django 4.2.11 on 2024-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_fornecedor_cnpj_fornecedor_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=16),
        ),
    ]
