# Generated by Django 4.2.11 on 2024-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_itemnf_preco_unitario_alter_itemnf_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnf',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
