# Generated by Django 4.1.7 on 2023-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_remove_pedido_produto_remove_pedido_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaNome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPrateleira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localNome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setorNome', models.CharField(max_length=64)),
            ],
        ),
    ]
