# Generated by Django 4.1.7 on 2023-06-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_produto_categoria_produto_local_saida_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.fornecedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='almoxarifado.ProdutoPedido', to='almoxarifado.produto'),
        ),
    ]
