# Generated by Django 4.1.7 on 2023-06-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_remove_pedido_solicitante_pedido_fornecedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
