# Generated by Django 4.1.7 on 2023-08-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_delete_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
